server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://management.jonpad.com.cn:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
    password: top_summary
    username: 759282337@ffcs
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
