server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/top_summary?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
    password: 5R4MiECz5HwhEA7p
    username: top_summary
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
