server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/top_summary?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
    password: a1955becdf28798c
    username: root
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
