spring:
  application:
    name: weibo-top-summary
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:mapper/**.xml
########## Mybatis 自身配置 ##########
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: partial
  mapper-locations: classpath:mapper/**.xml
  type-aliases-package: cn.com.jonpad.weibotopsummary.entities

app:
  client-id: clientapp
  client-secret: 123456
  auth-server: http://zuul-gateway:8088/authentication-service